name: reactive_ble_mobile
description: Official Android and iOS implementation for the flutter_reactive_ble plugin.
version: 5.5.0
homepage: https://github.com/xyhuangjia/flutter_reactive_ble

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^6.0.0
  reactive_ble_platform_interface: ^5.5.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14

dependency_overrides:
  reactive_ble_platform_interface:
    path: ../reactive_ble_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: com.signify.hue.flutterreactiveble
        pluginClass: ReactiveBlePlugin
      ios:
        pluginClass: ReactiveBlePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: ReactiveBlePlugin
        sharedDarwinSource: true  
