name: reactive_ble_platform_interface
description: Platform interface for the flutter_reactive_ble_project 
version: 5.5.0
homepage: https://github.com/xyhuangjia/flutter_reactive_ble

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.29.2"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  functional_data: ^1.2.0
  meta: ^1.17.0

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  mockito: ^5.0.2

flutter:
